In [1]:
import numpy as np

In [2]:
def double(L):
    for x in L:
        yield x*2

In [4]:
L = list(range(6))
L

[0, 1, 2, 3, 4, 5]

In [8]:
for item in double(L):
    print(item)
    print('____')

0
____
2
____
4
____
6
____
8
____
10
____


In [9]:
double(L)

<generator object double at 0x7f7ce409b468>

In [10]:
type(range(6))

range

In [13]:
L.__iter__()

In [14]:
data_size = 100
batch_size = 7
for start_index, end_index in zip( \
                    range(0, data_size, batch_size),
                    range(batch_size, data_size, batch_size)
                    ):
    print(start_index, end_index)

0 7
7 14
14 21
21 28
28 35
35 42
42 49
49 56
56 63
63 70
70 77
77 84
84 91
91 98


In [2]:
a = [2,3,4]
b = [5,6,7]

In [4]:
np.hstack((a,b))

array([2, 3, 4, 5, 6, 7])

In [5]:
np.vstack((a,b))

array([[2, 3, 4],
       [5, 6, 7]])

In [6]:
np.vstack((a,b)).T

array([[2, 5],
       [3, 6],
       [4, 7]])